version: '3.8'

services:

  meta_db:
    image: postgres:17
    container_name: meta_db
    environment:
      POSTGRES_DB: gym_meta
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym123
    ports:
      - "5430:5432"

  shard_node_1:
    image: postgres:17
    container_name: shard_node_1
    environment:
      POSTGRES_DB: gym_shard
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym123
    ports:
      - "5431:5432"

  shard_node_2:
    image: postgres:17
    container_name: shard_node_2
    environment:
      POSTGRES_DB: gym_shard
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym123
    ports:
      - "5435:5432"

  shard_node_3:
    image: postgres:17
    container_name: shard_node_3
    environment:
      POSTGRES_DB: gym_shard
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym123
    ports:
      - "5434:5432"