-- =============================================
-- GYM SYSTEM — SHARD SCHEMA
-- This file is run on every shard node
-- Shard ID: 0
-- =============================================


-- =============================================
-- 1. CREATE SCHEMA FOR THIS SHARD
-- =============================================

CREATE SCHEMA IF NOT EXISTS shard_0;


-- =============================================
-- 2. SEQUENCE
-- 10 bits = 0 to 1023
-- cycles back to 0 after 1023
-- one sequence per shard schema
-- =============================================

CREATE SEQUENCE IF NOT EXISTS shard_0.id_seq
    START 0
    MINVALUE 0
    MAXVALUE 1023
    CYCLE;


-- =============================================
-- 3. SNOWFLAKE ID GENERATOR
-- 64 bit ID layout:
--   41 bits → timestamp ms from epoch
--   13 bits → shard_id
--   10 bits → sequence
-- =============================================

CREATE OR REPLACE FUNCTION shard_0.next_id(
    OUT result BIGINT
) AS $$
DECLARE
    -- Epoch: 2024-01-01 00:00:00 UTC
    -- All timestamps measured from this point
    our_epoch BIGINT := 1704067200000;

    seq_id   BIGINT;
    now_ms   BIGINT;
    shard_id INT := 0;

BEGIN
    -- Step 1: next sequence value for this shard
    SELECT nextval('shard_0.id_seq')
    INTO seq_id;

    -- Step 2: milliseconds since our epoch
    SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) - our_epoch
    INTO now_ms;

    -- Step 3: build 64 bit snowflake ID
    --
    -- timestamp occupies leftmost 41 bits
    -- shift left by 23 to make room for
    -- 13 bit shard + 10 bit sequence
    result := now_ms << 23;

    -- shard_id occupies next 13 bits
    -- shift left by 10 to make room for sequence
    result := result | (shard_id << 10);

    -- sequence occupies rightmost 10 bits
    result := result | seq_id;

END;
$$ LANGUAGE plpgsql;


-- =============================================
-- 4. DECODE FUNCTION
-- given any ID tell me:
--   which shard it came from
--   when it was created
--   what sequence it was
-- =============================================

CREATE OR REPLACE FUNCTION shard_0.decode_id(
    id         BIGINT,
    OUT shard  INT,
    OUT seq    INT,
    OUT created_at TIMESTAMPTZ
) AS $$
DECLARE
    our_epoch BIGINT := 1704067200000;
    now_ms BIGINT;
BEGIN
    -- extract timestamp: shift right 23 bits
    now_ms := (id >> 23) + our_epoch;

    -- extract shard_id: shift right 10, mask 13 bits
    shard := (id >> 10) & 8191;

    -- extract sequence: mask rightmost 10 bits
    seq := id & 1023;

    -- convert ms to timestamp
    created_at := TO_TIMESTAMP(now_ms / 1000.0)
                  AT TIME ZONE 'UTC';
END;
$$ LANGUAGE plpgsql;


-- =============================================
-- 5. MEMBERS TABLE
-- core user/member data
-- =============================================

CREATE TABLE IF NOT EXISTS shard_0.members (
    -- snowflake id generated by this shard
    id BIGINT DEFAULT shard_0.next_id() PRIMARY KEY,

    -- personal info
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(10),

    -- membership
    membership_plan VARCHAR(50) NOT NULL DEFAULT 'basic',
    -- basic | premium | vip

    membership_status VARCHAR(20) NOT NULL DEFAULT 'active',
    -- active | inactive | suspended

    -- location
    gym_branch VARCHAR(100),
    city VARCHAR(100),
    country VARCHAR(100) DEFAULT 'Kenya',

    -- timestamps
    -- no created_at needed for sorting
    -- snowflake ID encodes time already
    -- but useful for human readable queries
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================
-- 6. CHECKINS TABLE
-- every time a member visits the gym
-- =============================================

CREATE TABLE IF NOT EXISTS shard_0.checkins (
    id BIGINT DEFAULT shard_0.next_id() PRIMARY KEY,

    -- links back to member on same shard
    -- member and their checkins
    -- always co-located ✅
    member_id BIGINT NOT NULL,

    gym_branch VARCHAR(100),

    -- checkin and checkout times
    checked_in_at TIMESTAMPTZ DEFAULT NOW(),
    checked_out_at TIMESTAMPTZ,

    -- how long they stayed in minutes
    duration_minutes INT
        GENERATED ALWAYS AS (
            EXTRACT(EPOCH FROM (checked_out_at - checked_in_at)) / 60
        ) STORED
);


-- =============================================
-- 7. MEMBERSHIP PAYMENTS TABLE
-- billing per member
-- co-located with member ✅
-- =============================================

CREATE TABLE IF NOT EXISTS shard_0.payments (
    id BIGINT DEFAULT shard_0.next_id() PRIMARY KEY,

    member_id BIGINT NOT NULL,

    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'KES',

    payment_status VARCHAR(20) DEFAULT 'pending',
    -- pending | paid | failed | refunded

    payment_method VARCHAR(50), -- mpesa | card | cash

    -- mpesa specific
    mpesa_ref VARCHAR(50),

    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================
-- 8. INDEXES
-- only on columns we actually query
-- partial where it makes sense
-- =============================================

-- members: find by email (login)
CREATE UNIQUE INDEX IF NOT EXISTS
    idx_0_members_email
    ON shard_0.members (email);

-- members: find active members only
-- partial index — we rarely query inactive
CREATE INDEX IF NOT EXISTS
    idx_0_members_active
    ON shard_0.members (membership_status)
    WHERE membership_status = 'active';

-- checkins: find all checkins for a member
-- most common query: "show me John's checkins"
CREATE INDEX IF NOT EXISTS
    idx_0_checkins_member
    ON shard_0.checkins (member_id);

-- checkins: find todays checkins
-- BRIN because created_at is time series
CREATE INDEX IF NOT EXISTS
    idx_0_checkins_time
    ON shard_0.checkins
    USING BRIN (checked_in_at);

-- payments: find pending payments
-- partial index — only unpaid rows
CREATE INDEX IF NOT EXISTS
    idx_0_payments_pending
    ON shard_0.payments (member_id)
    WHERE payment_status = 'pending';
